# Generated by Django 4.1.3 on 2022-11-18 09:37

from django.db import migrations

def load_initial_data(apps, schema_editor):
    # get our model
    # get_model(appname, modelname)
    item_model = apps.get_model('payments', 'Item')
    item_model.objects.create (
        name = "Ball", description = "awesome ball", price=100
        )
    item_model.objects.create (
        name = "Stick", description = "awesome stick", price=200
        )
    item_model.objects.create (
        name = "Helmet", description = "awesome helmet", price=300
        )

class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(load_initial_data),
        ]
